FROM rasa/rasa-sdk:3.6.0

# Set working directory
WORKDIR /app

# Copy actions file
COPY actions /app/actions

# Set environment variables
ENV RASA_ACTION_PORT=5055
ENV RASA_ACTION_HOST=0.0.0.0

# Expose the port
EXPOSE 5055

